### ISSUE TITLE
user research and interview

### ISSUE THREAD

**Issue by t-c-team79** [t-c-team79/terms-and-condition-website-team-79#3]
create the research survey using Google survey. Also screen everyone that filled the survey form to determine who our target audience are. Also study our target audience to collect and analyze data that will help inform our design process.

**Comment by AdeolaJoan** [comment]
Already done
1. Survey Form [https://forms.gle/8MBQTcKWy6z4Nyfo6](url)
2. Research Plan Template link[https://tinyurl.com/43zfhth2](url)
